queue_rules:
  - name: default
    queue_conditions:
      - base=main
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - check-success='lint-test'
      - check-success='build'
      - label!=do-not-merge
      - label=ready-to-merge
    merge_conditions:
      # Conditions to get out of the queue (= merged)
      - check-success=lint-test
      - check-success=build
    commit_message_template: |
      {{ title }} (#{{ number }})
    merge_method: merge

pull_request_rules:
  - name: Automatic merge on approval
    conditions: []
    actions:
      queue:
