package dell

import "github.com/packethost/ironlib/model"

// nolint // test data
var (
	// data from test_data/r6515/*
	testdata_R6515Inventory = &model.Device{
		HardwareType: "",
		Vendor:       "Dell Inc.",
		Model:        "PowerEdge R6515 (SKU=NotProvided;ModelName=PowerEdge R6515)",
		Serial:       "11WLK93",
		Chassis:      "",
		BIOS: &model.BIOS{
			Description:   "BIOS",
			Vendor:        "Dell Inc.",
			SizeBytes:     65536,
			CapacityBytes: 33554432,
			Firmware: &model.Firmware{
				Available: "",
				Installed: "1.7.4",
				Managed:   true,
			},
		},
		BMC: &model.BMC{
			Description: "",
			Vendor:      "",
			Firmware: &model.Firmware{
				Available: "",
				Installed: "4.40.00.00",
				Managed:   true,
			},
		},
		TPM: &model.TPM{},
		Mainboard: &model.Mainboard{
			ProductName: "",
			Description: "Motherboard",
			Vendor:      "Dell Inc.",
			Model:       "0R4CNN",
			Serial:      ".11WLK93.CNCMS0009G0078.",
			PhysicalID:  "0",
		},
		GPUs: []*model.GPU{},
		CPUs: []*model.CPU{
			{
				Description:  "AMD EPYC 7502P 32-Core Processor",
				Vendor:       "Advanced Micro Devices [AMD]",
				Model:        "AMD EPYC 7502P 32-Core Processor",
				Serial:       "",
				Slot:         "CPU1",
				ClockSpeedHz: 2000000000,
				Cores:        32,
				Threads:      64,
			},
		},
		Memory: []*model.Memory{
			{
				Description:  "DIMM DDR4 Synchronous Registered (Buffered) 3200 MHz (0.3 ns)",
				Slot:         "A1",
				Type:         "",
				Vendor:       "Hynix Semiconductor (Hyundai Electronics)",
				Model:        "HMA84GR7DJR4N-XN",
				Serial:       "3510CB7F",
				SizeBytes:    34359738368,
				FormFactor:   "",
				PartNumber:   "",
				ClockSpeedHz: 3200000000,
			},
			{
				Description:  "DIMM DDR4 Synchronous Registered (Buffered) 3200 MHz (0.3 ns)",
				Slot:         "A2",
				Type:         "",
				Vendor:       "Hynix Semiconductor (Hyundai Electronics)",
				Model:        "HMA84GR7DJR4N-XN",
				Serial:       "3510CBDD",
				SizeBytes:    34359738368,
				FormFactor:   "",
				PartNumber:   "",
				ClockSpeedHz: 3200000000,
			},
			{
				Description:  "DIMM DDR4 Synchronous Registered (Buffered) 3200 MHz (0.3 ns)",
				Slot:         "A3",
				Type:         "",
				Vendor:       "Hynix Semiconductor (Hyundai Electronics)",
				Model:        "HMA84GR7DJR4N-XN",
				Serial:       "3510CC97",
				SizeBytes:    34359738368,
				FormFactor:   "",
				PartNumber:   "",
				ClockSpeedHz: 3200000000,
			},
			{
				Description:  "DIMM DDR4 Synchronous Registered (Buffered) 3200 MHz (0.3 ns)",
				Slot:         "A4",
				Type:         "",
				Vendor:       "Hynix Semiconductor (Hyundai Electronics)",
				Model:        "HMA84GR7DJR4N-XN",
				Serial:       "3510CC8C",
				SizeBytes:    34359738368,
				FormFactor:   "",
				PartNumber:   "",
				ClockSpeedHz: 3200000000,
			},
			{
				Description:  "DIMM DDR4 Synchronous Registered (Buffered) 3200 MHz (0.3 ns)",
				Slot:         "A5",
				Type:         "",
				Vendor:       "Hynix Semiconductor (Hyundai Electronics)",
				Model:        "HMA84GR7DJR4N-XN",
				Serial:       "3510CBDE",
				SizeBytes:    34359738368,
				FormFactor:   "",
				PartNumber:   "",
				ClockSpeedHz: 3200000000,
			},
			{
				Description:  "DIMM DDR4 Synchronous Registered (Buffered) 3200 MHz (0.3 ns)",
				Slot:         "A6",
				Type:         "",
				Vendor:       "Hynix Semiconductor (Hyundai Electronics)",
				Model:        "HMA84GR7DJR4N-XN",
				Serial:       "3510CB77",
				SizeBytes:    34359738368,
				FormFactor:   "",
				PartNumber:   "",
				ClockSpeedHz: 3200000000,
			},
			{
				Description:  "DIMM DDR4 Synchronous Registered (Buffered) 3200 MHz (0.3 ns)",
				Slot:         "A7",
				Type:         "",
				Vendor:       "Hynix Semiconductor (Hyundai Electronics)",
				Model:        "HMA84GR7DJR4N-XN",
				Serial:       "3510CC78",
				SizeBytes:    34359738368,
				FormFactor:   "",
				PartNumber:   "",
				ClockSpeedHz: 3200000000,
			},
			{
				Description:  "DIMM DDR4 Synchronous Registered (Buffered) 3200 MHz (0.3 ns)",
				Slot:         "A8",
				Type:         "",
				Vendor:       "Hynix Semiconductor (Hyundai Electronics)",
				Model:        "HMA84GR7DJR4N-XN",
				Serial:       "3510CC93",
				SizeBytes:    34359738368,
				FormFactor:   "",
				PartNumber:   "",
				ClockSpeedHz: 3200000000,
			},
			{
				Description:  "[empty]",
				Slot:         "A9",
				Type:         "",
				Vendor:       "",
				Model:        "",
				Serial:       "",
				SizeBytes:    0,
				FormFactor:   "",
				PartNumber:   "",
				ClockSpeedHz: 0,
			},
			{
				Description:  "[empty]",
				Slot:         "A10",
				Type:         "",
				Vendor:       "",
				Model:        "",
				Serial:       "",
				SizeBytes:    0,
				FormFactor:   "",
				PartNumber:   "",
				ClockSpeedHz: 0,
			},
			{
				Description:  "[empty]",
				Slot:         "A11",
				Type:         "",
				Vendor:       "",
				Model:        "",
				Serial:       "",
				SizeBytes:    0,
				FormFactor:   "",
				PartNumber:   "",
				ClockSpeedHz: 0,
			},
			{
				Description:  "[empty]",
				Slot:         "A12",
				Type:         "",
				Vendor:       "",
				Model:        "",
				Serial:       "",
				SizeBytes:    0,
				FormFactor:   "",
				PartNumber:   "",
				ClockSpeedHz: 0,
			},
			{
				Description:  "[empty]",
				Slot:         "A13",
				Type:         "",
				Vendor:       "",
				Model:        "",
				Serial:       "",
				SizeBytes:    0,
				FormFactor:   "",
				PartNumber:   "",
				ClockSpeedHz: 0,
			},
			{
				Description:  "[empty]",
				Slot:         "A14",
				Type:         "",
				Vendor:       "",
				Model:        "",
				Serial:       "",
				SizeBytes:    0,
				FormFactor:   "",
				PartNumber:   "",
				ClockSpeedHz: 0,
			},
			{
				Description:  "[empty]",
				Slot:         "A15",
				Type:         "",
				Vendor:       "",
				Model:        "",
				Serial:       "",
				SizeBytes:    0,
				FormFactor:   "",
				PartNumber:   "",
				ClockSpeedHz: 0,
			},
			{
				Description:  "[empty]",
				Slot:         "A16",
				Type:         "",
				Vendor:       "",
				Model:        "",
				Serial:       "",
				SizeBytes:    0,
				FormFactor:   "",
				PartNumber:   "",
				ClockSpeedHz: 0,
			},
		},
		NICs: []*model.NIC{
			{
				Description: "Ethernet interface",
				Vendor:      "Intel Corporation",
				Model:       "Ethernet Controller XXV710 for 25GbE SFP28",
				Serial:      "40:a6:b7:4e:8a:a0",
				SpeedBits:   0,
				PhysicalID:  "0",
				Oem:         true,
				Firmware: &model.Firmware{
					Available: "",
					Installed: "20.0.17",
					Managed:   true,
				},
			},
			{
				Description: "Ethernet interface",
				Vendor:      "Intel Corporation",
				Model:       "Ethernet Controller XXV710 for 25GbE SFP28",
				Serial:      "40:a6:b7:4e:8a:a0",
				SpeedBits:   0,
				PhysicalID:  "0.1",
				Oem:         true,
				Firmware: &model.Firmware{
					Available: "",
					Installed: "20.0.17",
					Managed:   true,
				},
			},
		},
		Drives: []*model.Drive{
			{
				Description:       "NVMe device",
				Serial:            "202728F691F5",
				StorageController: "",
				Vendor:            "Micron Technology Inc",
				Model:             "Micron_9300_MTFDHAL3T8TDP",
				WWN:               "",
				SizeBytes:         0,
				CapacityBytes:     0,
				BlockSize:         0,
				Oem:               true,
				Firmware: &model.Firmware{
					Available: "",
					Installed: "D3DJ004",
					Managed:   true,
				},
			},
			{
				Description:       "NVMe device",
				Serial:            "202728F691C6",
				StorageController: "",
				Vendor:            "Micron Technology Inc",
				Model:             "Micron_9300_MTFDHAL3T8TDP",
				WWN:               "",
				SizeBytes:         0,
				CapacityBytes:     0,
				BlockSize:         0,
				Oem:               true,
				Firmware: &model.Firmware{
					Available: "",
					Installed: "D3DJ004",
					Managed:   true,
				},
			},
			{
				Description:       "ATA Disk",
				Serial:            "203329F89392",
				StorageController: "",
				Vendor:            "",
				Model:             "MTFDDAV240TDU",
				WWN:               "",
				SizeBytes:         240057409536,
				CapacityBytes:     0,
				BlockSize:         0,
				Oem:               true,
				Firmware: &model.Firmware{
					Available: "",
					Installed: "D3DJ004",
					Managed:   true,
				},
			},
			{
				Description:       "ATA Disk",
				Serial:            "203329F89796",
				StorageController: "",
				Vendor:            "",
				Model:             "MTFDDAV240TDU",
				WWN:               "",
				SizeBytes:         240057409536,
				CapacityBytes:     0,
				BlockSize:         0,
				Oem:               true,
				Firmware: &model.Firmware{
					Available: "",
					Installed: "D3DJ004",
					Managed:   true,
				},
			},
		},
		StorageControllers: []*model.StorageController{
			{
				Description: "Serial Attached SCSI controller",
				Vendor:      "Broadcom / LSI",
				Model:       "SAS3008 PCI-Express Fusion-MPT SAS-3",
				Serial:      "",
				Interface:   "SAS",
				PhysicalID:  "0",
				Oem:         true,
				Firmware: &model.Firmware{
					Available: "",
					Installed: "16.17.01.00",
					Managed:   true,
				},
			},
			{
				Description: "SATA controller",
				Vendor:      "Advanced Micro Devices, Inc. [AMD]",
				Model:       "FCH SATA Controller [AHCI mode]",
				Serial:      "",
				Interface:   "SATA",
				PhysicalID:  "0",
				Oem:         true,
				Firmware: &model.Firmware{
					Available: "",
					Installed: "16.17.01.00",
					Managed:   true,
				},
			},
			{
				Description: "SATA controller",
				Vendor:      "Advanced Micro Devices, Inc. [AMD]",
				Model:       "FCH SATA Controller [AHCI mode]",
				Serial:      "",
				Interface:   "SATA",
				PhysicalID:  "0",
				Oem:         true,
				Firmware: &model.Firmware{
					Available: "",
					Installed: "16.17.01.00",
					Managed:   true,
				},
			},
			{
				Description: "SATA controller",
				Vendor:      "Marvell Technology Group Ltd.",
				Model:       "88SE9230 PCIe SATA 6Gb/s Controller",
				Serial:      "",
				Interface:   "SATA",
				PhysicalID:  "0",
				Oem:         true,
				Firmware: &model.Firmware{
					Available: "",
					Installed: "16.17.01.00",
					Managed:   true,
				},
			},
		},
		Oem: false,
		OemComponents: &model.OemComponents{
			Dell: []*model.Component{
				{

					Name:              "BOSS",
					Slug:              "Boss Adapter",
					FirmwareInstalled: "2.5.13.3024",
					FirmwareAvailable: "",
					Oem:               true,
					FirmwareManaged:   true,
				},
				{

					Name:              "SEP Firmware, BayID: 1",
					Slug:              "Non-Expander Storage Backplane (SEP)",
					FirmwareInstalled: "4.35",
					FirmwareAvailable: "",
					Oem:               true,
					FirmwareManaged:   true,
				},
				{

					Name:              "Firmware for  - Disk 0 of BOSS Adapter",
					Slug:              "Boss Adapter - Disk 0",
					FirmwareInstalled: "J004",
					FirmwareAvailable: "",
					Oem:               true,
					FirmwareManaged:   true,
				},
				{

					Name:              "Firmware for  - Disk 1 of BOSS Adapter",
					Slug:              "Boss Adapter",
					FirmwareInstalled: "J004",
					FirmwareAvailable: "",
					Oem:               true,
					FirmwareManaged:   true,
				},
				{

					Name:              "Lifecycle Controller",
					Slug:              "Lifecycle Controller",
					FirmwareInstalled: "4.40.00.00",
					FirmwareAvailable: "",
					Oem:               true,
					FirmwareManaged:   true,
				},
				{

					Name:              "Dell 64 Bit uEFI Diagnostics, version 4301, 4301A50, 4301.51",
					Slug:              "Dell 64 bit uEFI diagnostics",
					FirmwareInstalled: "4301A50",
					FirmwareAvailable: "",
					Oem:               true,
					FirmwareManaged:   true,
				},
				{

					Name:              "OS COLLECTOR, v5.0, A00",
					Slug:              "OS Collector",
					FirmwareInstalled: "5.0",
					FirmwareAvailable: "",
					Oem:               true,
					FirmwareManaged:   true,
				},
				{

					Name:              "Dell EMC iDRAC Service Module Embedded Package v3.5.1, A00",
					Slug:              "IDrac Service Module",
					FirmwareInstalled: "3.5.1",
					FirmwareAvailable: "",
					Oem:               true,
					FirmwareManaged:   true,
				},
				{
					Name:              "System CPLD",
					Slug:              "Dell System CPLD",
					FirmwareInstalled: "1.0.3",
					FirmwareAvailable: "",
					Oem:               true,
					FirmwareManaged:   true,
				},
			},
		},
		PSUs: []*model.PSU{},
	}
)
