// Code generated by "stringer -type SanitizeAction"; DO NOT EDIT.

package utils

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Invalid-0]
	_ = x[ExitFailureMode-1]
	_ = x[BlockErase-2]
	_ = x[Overwrite-3]
	_ = x[CryptoErase-4]
}

const _SanitizeAction_name = "InvalidExitFailureModeBlockEraseOverwriteCryptoErase"

var _SanitizeAction_index = [...]uint8{0, 7, 22, 32, 41, 52}

func (i SanitizeAction) String() string {
	if i >= SanitizeAction(len(_SanitizeAction_index)-1) {
		return "SanitizeAction(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SanitizeAction_name[_SanitizeAction_index[i]:_SanitizeAction_index[i+1]]
}
