// Code generated by "stringer -type SecureEraseSetting"; DO NOT EDIT.

package utils

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[None-0]
	_ = x[UserDataErase-1]
	_ = x[CryptographicErase-2]
	_ = x[Reserved-3]
}

const _SecureEraseSetting_name = "NoneUserDataEraseCryptographicEraseReserved"

var _SecureEraseSetting_index = [...]uint8{0, 4, 17, 35, 43}

func (i SecureEraseSetting) String() string {
	if i >= SecureEraseSetting(len(_SecureEraseSetting_index)-1) {
		return "SecureEraseSetting(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SecureEraseSetting_name[_SecureEraseSetting_index[i]:_SecureEraseSetting_index[i+1]]
}
