package utils

import (
	"bytes"
	"context"
	"io/ioutil"
	"testing"

	"github.com/stretchr/testify/assert"
)

func Test_parseSMCBIOSConfig_X11SCHFF(t *testing.T) {
	expected := map[string]string{"boot_mode": "BIOS",
		"intel_sgx":                                 "Software Controlled",
		"secure_boot":                               "Disabled",
		"smt":                                       "Enabled",
		"tpm":                                       "Enabled",
		"raw:AES":                                   "Enabled",
		"raw:ASPM":                                  "Auto",
		"raw:ASPM L0s":                              "Both Root and Endpoint Ports",
		"raw:Above 4GB MMIO BIOS assignment":        "Disabled",
		"raw:Active Processor Cores":                "All",
		"raw:Adjacent Cache Line Prefetch":          "Enabled",
		"raw:Aggressive LPM Support":                "Disabled",
		"raw:Always Turbo Mode":                     "Disabled",
		"raw:BIST":                                  "Disabled",
		"raw:BME DMA Mitigation":                    "Disabled",
		"raw:Bits per second":                       "115200",
		"raw:Boot Option #1":                        "IBA GE Slot 0400 v1404",
		"raw:Boot Option #2":                        "FlexBoot v3.6.102 (PCI 02:00.0)",
		"raw:Boot Option #3":                        "FlexBoot v3.6.102 (PCI 02:00.1)",
		"raw:Boot Performance Mode":                 "Max Non-Turbo Performance",
		"raw:Bootup NumLock State":                  "Enabled",
		"raw:C states":                              "Enabled",
		"raw:C-State Auto Demotion":                 "C1 and C3",
		"raw:C-State Un-demotion":                   "C1 and C3",
		"raw:CPU Flex Ratio Override":               "Disabled",
		"raw:CPU SLOT5 PCI-E 3.0 X8 OPROM":          "Legacy",
		"raw:CState Pre-Wake":                       "Enabled",
		"raw:Change Settings":                       "Auto",
		"raw:DMI De-emphasis Control":               "-3.5 dB",
		"raw:DMI Extended Sync Control":             "Disabled",
		"raw:DMI Link ASPM Control":                 "Auto",
		"raw:DUAL Boot Option #1":                   "Hard Disk: Micron_5300_MTFDDAK480TDT",
		"raw:DUAL Boot Option #10":                  "UEFI CD/DVD",
		"raw:DUAL Boot Option #11":                  "UEFI USB Hard Disk",
		"raw:DUAL Boot Option #12":                  "UEFI USB CD/DVD",
		"raw:DUAL Boot Option #13":                  "UEFI USB Key",
		"raw:DUAL Boot Option #14":                  "UEFI USB Floppy",
		"raw:DUAL Boot Option #15":                  "UEFI USB Lan",
		"raw:DUAL Boot Option #16":                  "UEFI Network",
		"raw:DUAL Boot Option #17":                  "UEFI AP:UEFI: Built-in EFI Shell",
		"raw:DUAL Boot Option #2":                   "CD/DVD",
		"raw:DUAL Boot Option #3":                   "USB Hard Disk",
		"raw:DUAL Boot Option #4":                   "USB CD/DVD",
		"raw:DUAL Boot Option #5":                   "USB Key",
		"raw:DUAL Boot Option #6":                   "USB Floppy",
		"raw:DUAL Boot Option #7":                   "USB Lan",
		"raw:DUAL Boot Option #8":                   "Network:IBA GE Slot 0400 v1404",
		"raw:DUAL Boot Option #9":                   "UEFI Hard Disk",
		"raw:Data Bits":                             "8",
		"raw:De-emphasis Control":                   "-3.5 dB",
		"raw:DeepSx Power Policies":                 "Disabled",
		"raw:Device Select":                         "Auto",
		"raw:Enable Root Port":                      "Auto",
		"raw:Endorsement Hierarchy":                 "Enabled",
		"raw:Enhanced C-states":                     "Enabled",
		"raw:Erase Event Log":                       "No",
		"raw:Fast Boot":                             "Enabled",
		"raw:Flow Control":                          "None",
		"raw:GNA Device (B0:D8:F0)":                 "Enabled",
		"raw:HTTP Boot One Time":                    "Disabled",
		"raw:Hard Drive Security Frozen":            "Disabled",
		"raw:Hardware Prefetcher":                   "Enabled",
		"raw:High Precision Event Timer":            "Enabled",
		"raw:IPSEC Certificate":                     "Disabled",
		"raw:IPv4 HTTP Support":                     "Disabled",
		"raw:IPv4 PXE Support":                      "Enabled",
		"raw:IPv6 HTTP Support":                     "Disabled",
		"raw:IPv6 PXE Support":                      "Enabled",
		"raw:Intel (VMX) Virtualization Technology": "Enabled",
		"raw:Intel(R) Speed Shift Technology":       "Disabled",
		"raw:Intel(R) SpeedStep(tm)":                "Enabled",
		"raw:Internal Graphics":                     "Enabled",
		"raw:Legacy Boot Option #1":                 "Network:IBA GE Slot 0400 v1404",
		"raw:Legacy Boot Option #2":                 "Hard Disk: Micron_5300_MTFDDAK480TDT",
		"raw:Legacy Boot Option #3":                 "Disabled",
		"raw:Legacy Boot Option #4":                 "Disabled",
		"raw:Legacy Boot Option #5":                 "Disabled",
		"raw:Legacy Boot Option #6":                 "Disabled",
		"raw:Legacy Boot Option #7":                 "Disabled",
		"raw:Legacy Boot Option #8":                 "Disabled",
		"raw:Legacy OS Redirection Resolution":      "80x25",
		"raw:Legacy USB Support":                    "Enabled",
		"raw:Log System Boot Event":                 "Disabled",
		"raw:M.2-P_1 OPROM":                         "Legacy",
		"raw:M.2-P_2 OPROM":                         "Legacy",
		"raw:Max Link Speed":                        "Auto",
		"raw:Max Link Width":                        "Auto",
		"raw:Max Payload size":                      "Auto",
		"raw:Max TOLUD":                             "Dynamic",
		"raw:Maximum Memory Frequency":              "Auto",
		"raw:Memory Corrected Error Enabling":       "Disabled",
		"raw:Memory Scrambler":                      "Enabled",
		"raw:Monitor/Mwait":                         "Enabled",
		"raw:NVMe Firmware Source":                  "Vendor Defined Firmware",
		"raw:Native ASPM":                           "Auto",
		"raw:Native PCIE Enable":                    "Enabled",
		"raw:Network Stack":                         "Enabled",
		"raw:Onboard LAN Option ROM Type":           "Legacy",
		"raw:Onboard LAN1 Option ROM":               "PXE",
		"raw:Onboard LAN1 Support":                  "Enabled",
		"raw:Onboard LAN2 Option ROM":               "Disabled",
		"raw:Onboard LAN2 Support":                  "Enabled",
		"raw:Onboard Video Option ROM":              "Legacy",
		"raw:Option ROM Messages":                   "Force BIOS",
		"raw:Out-of-Band Mgmt Port":                 "COM1",
		"raw:PCI AER Support":                       "Disabled",
		"raw:PCI PERR/SERR Support":                 "Disabled",
		"raw:PCIe PLL SSC":                          "Enabled",
		"raw:PH Randomization":                      "Enabled",
		"raw:PRMRR Size":                            "128MB",
		"raw:Package C State Limit":                 "Auto",
		"raw:Package C-State Demotion":              "Disabled",
		"raw:Package C-State Un-demotion":           "Disabled",
		"raw:Parity":                                "None",
		"raw:Password Check":                        "Setup",
		"raw:Peer Memory Write Enable":              "Disabled",
		"raw:Pending Operation":                     "None",
		"raw:Physical Presence Spec Version":        "1.3",
		"raw:Platform Hierarchy":                    "Enabled",
		"raw:Port 0 Hot Plug":                       "Enabled",
		"raw:Port 0 SATA Device Type":               "Hard Disk Drive",
		"raw:Port 0 Spin Up Device":                 "Disabled",
		"raw:Port 1 Hot Plug":                       "Enabled",
		"raw:Port 1 SATA Device Type":               "Hard Disk Drive",
		"raw:Port 1 Spin Up Device":                 "Disabled",
		"raw:Port 2 Hot Plug":                       "Enabled",
		"raw:Port 2 SATA Device Type":               "Hard Disk Drive",
		"raw:Port 2 Spin Up Device":                 "Disabled",
		"raw:Port 3 Hot Plug":                       "Enabled",
		"raw:Port 3 SATA Device Type":               "Hard Disk Drive",
		"raw:Port 3 Spin Up Device":                 "Disabled",
		"raw:Port 4 Hot Plug":                       "Enabled",
		"raw:Port 4 SATA Device Type":               "Hard Disk Drive",
		"raw:Port 4 Spin Up Device":                 "Disabled",
		"raw:Port 5 Hot Plug":                       "Enabled",
		"raw:Port 5 SATA Device Type":               "Hard Disk Drive",
		"raw:Port 5 Spin Up Device":                 "Disabled",
		"raw:Port 6 Hot Plug":                       "Enabled",
		"raw:Port 6 SATA Device Type":               "Hard Disk Drive",
		"raw:Port 6 Spin Up Device":                 "Disabled",
		"raw:Port 60/64 Emulation":                  "Enabled",
		"raw:Port 61h Bit-4 Emulation":              "Enabled",
		"raw:Port 7 Hot Plug":                       "Enabled",
		"raw:Port 7 SATA Device Type":               "Hard Disk Drive",
		"raw:Port 7 Spin Up Device":                 "Disabled",
		"raw:Power Button Function":                 "Instant Off",
		"raw:Power Limit 1 Override":                "Disabled",
		"raw:Power Limit 1 Time Window":             "0",
		"raw:Power Limit 2 Override":                "Enabled",
		"raw:Power Limit Scale":                     "1.0x",
		"raw:Program PCIe ASPM after OpROM":         "Disabled",
		"raw:Putty KeyPad":                          "VT100",
		"raw:REFRESH_2X_MODE":                       "Disabled",
		"raw:RSC-RR1U-E16 OPROM":                    "Legacy",
		"raw:Re-try Boot":                           "Disabled",
		"raw:Redirection After BIOS POST":           "Always Enable",
		"raw:Redirection COM Port":                  "COM1",
		"raw:Reset Keys Type":                       "Disabled",
		"raw:Restore on AC Power Loss":              "Last State",
		"raw:SATA Controller(s)":                    "Enabled",
		"raw:SATA Interrupt Selection":              "MSI",
		"raw:SATA Mode Selection":                   "AHCI",
		"raw:SGX Launch Control Policy":             "Unlocked",
		"raw:SHA-1 PCR Bank":                        "Enabled",
		"raw:SHA256 PCR Bank":                       "Enabled",
		"raw:SMBIOS Event Log":                      "Enabled",
		"raw:SMCI BIOS-Based TPM Provision Support": "Disabled",
		"raw:Secure Boot Mode":                      "Setup",
		"raw:Security Function":                     "Disabled",
		"raw:Select Owner EPOCH input type":         "No Change in Owner EPOCHs",
		"raw:Serial Port 2 Attribute":               "SOL",
		"raw:Stop Bits":                             "1",
		"raw:Storage Hierarchy":                     "Enabled",
		"raw:Storage Option ROM/UEFI Driver":        "Legacy",
		"raw:TPM2.0 UEFI Spec Version":              "TCG_2",
		"raw:TXT Support":                           "Disabled",
		"raw:Terminal Type":                         "VT-UTF8",
		"raw:Turbo Mode":                            "Enabled",
		"raw:UEFI Boot Option #1":                   "UEFI Hard Disk",
		"raw:UEFI Boot Option #2":                   "UEFI AP:UEFI: Built-in EFI Shell",
		"raw:UEFI Boot Option #3":                   "UEFI CD/DVD",
		"raw:UEFI Boot Option #4":                   "UEFI USB Hard Disk",
		"raw:UEFI Boot Option #5":                   "UEFI USB CD/DVD",
		"raw:UEFI Boot Option #6":                   "UEFI USB Key",
		"raw:UEFI Boot Option #7":                   "UEFI USB Floppy",
		"raw:UEFI Boot Option #8":                   "UEFI USB Lan",
		"raw:UEFI Boot Option #9":                   "UEFI Network",
		"raw:USB Mass Storage Driver Support":       "Enabled",
		"raw:VGA Priority":                          "Onboard",
		"raw:VT-d":                                  "Enabled",
		"raw:WHEA Support":                          "Enabled",
		"raw:Wait For \"F1\" If Error":              "Enabled",
		"raw:Watch Dog Function":                    "Disabled",
		"raw:When Log is Full":                      "Do Nothing",
		"raw:X2APIC Opt Out":                        "Disabled",
		"raw:XHCI Hand-off":                         "Enabled",
	}

	b, err := ioutil.ReadFile("../fixtures/supermicro/x11schf-f/bios.xml")
	if err != nil {
		t.Error(err)
	}

	s := NewFakeSMCSum(bytes.NewReader(b))
	c, err := s.parseBIOSConfig(context.TODO())
	assert.NoError(t, err)
	assert.Equal(t, expected, c)
}

func Test_parseSMCBIOSConfig_X11DPHT(t *testing.T) {
	expected := map[string]string{
		"boot_mode":                            "DUAL",
		"secure_boot":                          "Disabled",
		"smt":                                  "Enabled",
		"tpm":                                  "Enabled",
		"raw:2x Refresh":                       "Auto",
		"raw:ACS Control":                      "Enabled",
		"raw:ADC Sparing":                      "Disabled",
		"raw:AES-NI":                           "Enabled",
		"raw:ARI Support":                      "Enabled",
		"raw:ATS":                              "Enabled",
		"raw:Above 4G Decoding":                "Enabled",
		"raw:Adjacent Cache Prefetch":          "Enabled",
		"raw:Aggressive Link Power Management": "Disabled",
		"raw:Autonomous Core C-State":          "Disabled",
		"raw:Bits per second":                  "115200",
		"raw:Boot Option #1":                   "IBA 40-10G Slot 1A00 v1066",
		"raw:Boot Option #10":                  "UEFI CD/DVD",
		"raw:Boot Option #11":                  "UEFI USB Hard Disk",
		"raw:Boot Option #12":                  "UEFI USB CD/DVD",
		"raw:Boot Option #13":                  "UEFI USB Key",
		"raw:Boot Option #14":                  "UEFI USB Floppy",
		"raw:Boot Option #15":                  "UEFI USB Lan",
		"raw:Boot Option #16":                  "UEFI Network",
		"raw:Boot Option #17":                  "UEFI Hard Disk",
		"raw:Boot Option #2":                   "FlexBoot v3.5.901 (PCI D8:00.0)",
		"raw:Boot Option #3":                   "FlexBoot v3.5.901 (PCI D8:00.1)",
		"raw:Boot Option #4":                   "USB CD/DVD",
		"raw:Boot Option #5":                   "USB Key",
		"raw:Boot Option #6":                   "USB Floppy",
		"raw:Boot Option #7":                   "USB Lan",
		"raw:Boot Option #8":                   "Hard Disk: Micron_5200_MTFDDAK9",
		"raw:Boot Option #9":                   "UEFI AP:UEFI: Built-in EFI Shell",
		"raw:Bootup NumLock State":             "Enabled",
		"raw:Bus Master Enable":                "Enabled",
		"raw:CPU C6 report":                    "Auto",
		"raw:CPU1 M.2 C-1 PCI-E 3.0 X4 VMD":    "Disabled",
		"raw:CPU1 M.2 C-2 PCI-E 3.0 X4 VMD":    "Disabled",
		"raw:CPU1 SLOT 1 PCI-E 3.0 X8 OPROM":   "Legacy",
		"raw:CPU1 SLOT 3 PCI-E 3.0 X8 OPROM":   "Legacy",
		"raw:CPU1 SLOT 6 PCI-E 3.0 X8 OPROM":   "Legacy",
		"raw:CPU1 SLOT 7 PCI-E 3.0 X8 OPROM":   "Legacy",
		"raw:CPU1 SLOT1 PCI-E 3.0 X8 VMD":      "Disabled",
		"raw:CPU1 SLOT3 PCI-E 3.0 X8 VMD":      "Disabled",
		"raw:CPU1 SLOT6 PCI-E 3.0 X8 VMD":      "Disabled",
		"raw:CPU1 SLOT7 PCI-E 3.0 X8 VMD":      "Disabled",
		"raw:CPU2 SLOT 2 PCI-E 3.0 X16 OPROM":  "Legacy",
		"raw:CPU2 SLOT 4 PCI-E 3.0 X16 OPROM":  "Legacy",
		"raw:CPU2 SLOT 5 PCI-E 3.0 X16 OPROM":  "Legacy",
		"raw:CPU2 SLOT2 PCI-E 3.0 X16 VMD":     "Disabled",
		"raw:CPU2 SLOT4 PCI-E 3.0 X16 VMD":     "Disabled",
		"raw:CPU2 SLOT5 PCI-E 3.0 X16 VMD":     "Disabled",
		"raw:Change Settings":                  "Auto",
		"raw:Coherency Support (Non-Isoch)":    "Enabled",
		"raw:Configure SATA as":                "AHCI",
		"raw:Configure sSATA as":               "AHCI",
		"raw:DCU IP Prefetcher":                "Enabled",
		"raw:DCU Streamer Prefetcher":          "Enabled",
		"raw:Data Bits":                        "8",
		"raw:Data Scrambling for DDR4":         "Auto",
		"raw:Degrade Precedence":               "Topology Precedence",
		"raw:Disable Block Sid":                "Disabled",
		"raw:Disable TPH":                      "No",
		"raw:EIST PSD Function":                "HW_ALL",
		"raw:ENERGY_PERF_BIAS_CFG mode":        "Balanced Performance",
		"raw:EV DFX Features":                  "Disabled",
		"raw:Endorsement Hierarchy":            "Enabled",
		"raw:Enforce POR":                      "POR",
		"raw:Enhanced Halt State (C1E)":        "Enabled",
		"raw:Enhanced PPR":                     "Disabled",
		"raw:Erase Event Log":                  "No",
		"raw:Execute Disable Bit":              "Enabled",
		"raw:Extended APIC":                    "Disabled",
		"raw:Flow Control":                     "None",
		"raw:HTTP Boot One Time":               "Disabled",
		"raw:Hardware P-States":                "Disabled",
		"raw:Hardware Prefetcher":              "Enabled",
		"raw:High Precision Event Timer":       "Enabled",
		"raw:Hot Plug":                         "Enabled",
		"raw:Hot Plug Capable":                 "Disabled",
		"raw:IMC Interleaving":                 "Auto",
		"raw:INT19 Trap Response":              "Immediate",
		"raw:IO Directory Cache (IODC)":        "Auto",
		"raw:IOU0 (IIO PCIe Br1)":              "Auto",
		"raw:IOU1 (IIO PCIe Br2)":              "Auto",
		"raw:IOU2 (IIO PCIe Br3)":              "Auto",
		"raw:IPv4 HTTP Support":                "Disabled",
		"raw:IPv4 PXE Support":                 "Enabled",
		"raw:IPv6 HTTP Support":                "Disabled",
		"raw:IPv6 PXE Support":                 "Enabled",
		"raw:Install Windows 7 USB Support":    "Disabled",
		"raw:Intel Virtualization Technology":  "Enabled",
		"raw:Intel® VMD for Volume Management Device for PStack0": "Disabled",
		"raw:Intel® VMD for Volume Management Device for PStack1": "Disabled",
		"raw:Intel® VMD for Volume Management Device for PStack2": "Disabled",
		"raw:Intel® VMD for Volume Management Device for Pstack1": "Disabled",
		"raw:Intel® VT for Directed I/O (VT-d)":                   "Enabled",
		"raw:Interrupt Remapping":                                 "Enabled",
		"raw:Isoc Mode":                                           "Auto",
		"raw:KTI Prefetch":                                        "Enabled",
		"raw:LEGACY to EFI support":                               "Disabled",
		"raw:LLC Dead Line Alloc":                                 "Enabled",
		"raw:LLC Prefetch":                                        "Disabled",
		"raw:Legacy OS Redirection Resolution":                    "80x25",
		"raw:Legacy Serial Redirection Port":                      "COM1",
		"raw:Legacy USB Support":                                  "Enabled",
		"raw:Link L0p Enable":                                     "Auto",
		"raw:Link L1 Enable":                                      "Auto",
		"raw:Link Speed":                                          "Auto",
		"raw:Local/Remote Threshold":                              "Auto",
		"raw:Log System Boot Event":                               "Disabled",
		"raw:M.2-C1 PCI-E 3.0 X4 OPROM":                           "Legacy",
		"raw:M.2-C2 PCI-E 3.0 X4 OPROM":                           "Legacy",
		"raw:MMCFG Base":                                          "2G",
		"raw:MMIO High Base":                                      "56T",
		"raw:MMIO High Granularity Size":                          "256G",
		"raw:Maximum Read Request":                                "Auto",
		"raw:Memory Corrected Error Enabling":                     "Disabled",
		"raw:Memory Frequency":                                    "Auto",
		"raw:Memory Rank Sparing":                                 "Disabled",
		"raw:Mirror mode":                                         "Disabled",
		"raw:Monitor/Mwait":                                       "Auto",
		"raw:Multi Rank Sparing":                                  "Two Rank",
		"raw:NUMA":                                                "Enabled",
		"raw:NVMe Firmware Source":                                "Vendor Defined Firmware",
		"raw:Network Stack":                                       "Enabled",
		"raw:Onboard LAN Device":                                  "Enabled",
		"raw:Onboard LAN1 Option ROM":                             "PXE",
		"raw:Onboard LAN2 Option ROM":                             "Disabled",
		"raw:Onboard Video Option ROM":                            "Legacy",
		"raw:Operation Mode":                                      "Test and Repair",
		"raw:Option ROM Messages":                                 "Force BIOS",
		"raw:Out-of-Band Mgmt Port":                               "COM1",
		"raw:PCI AER Support":                                     "Disabled",
		"raw:PCI-E Completion Timeout Disable":                    "No",
		"raw:PCI-E Port Max Payload Size":                         "Auto",
		"raw:PCIe PLL SSC":                                        "Disabled",
		"raw:PH Randomization":                                    "Disabled",
		"raw:PPIN Control":                                        "Unlock/Enable",
		"raw:PPR Type":                                            "Hard PPR",
		"raw:Package C State":                                     "Auto",
		"raw:Page Policy":                                         "Auto",
		"raw:Panic and High Watermark":                            "1/2",
		"raw:Parity":                                              "None",
		"raw:PassThrough DMA":                                     "Enabled",
		"raw:Password Check":                                      "Setup",
		"raw:Patrol Scrub":                                        "Enabled",
		"raw:Pending Operation":                                   "None",
		"raw:Platform Hierarchy":                                  "Enabled",
		"raw:Port 60/64 Emulation":                                "Enabled",
		"raw:Port 61h Bit-4 Emulation":                            "Disabled",
		"raw:Posted Interrupt":                                    "Enabled",
		"raw:Power Button Function":                               "Instant Off",
		"raw:Power Performance Tuning":                            "OS Controls EPB",
		"raw:Power Technology":                                    "Energy Efficient",
		"raw:Prioritize TPH":                                      "Disabled",
		"raw:Putty KeyPad":                                        "VT100",
		"raw:Re-try Boot":                                         "Disabled",
		"raw:Redirection After BIOS POST":                         "Always Enable",
		"raw:Relaxed Ordering":                                    "Disabled",
		"raw:Reset Keys Type":                                     "Disabled",
		"raw:Restore on AC Power Loss":                            "Last State",
		"raw:SATA Controller":                                     "Enabled",
		"raw:SATA Device Type":                                    "Hard Disk Drive",
		"raw:SATA HDD Unlock":                                     "Enabled",
		"raw:SATA RAID Option ROM/UEFI Driver":                    "Legacy",
		"raw:SATA RSTe Boot Info":                                 "Enabled",
		"raw:SDDC":                                                "Disabled",
		"raw:SHA256 PCR Bank":                                     "Enabled",
		"raw:SMBIOS Event Log":                                    "Enabled",
		"raw:SMCI BIOS-Based TPM Provision Support":               "Disabled",
		"raw:SNC":                                   "Disabled",
		"raw:SR-IOV Support":                        "Disabled",
		"raw:Secure Boot Mode":                      "Setup",
		"raw:Security Function":                     "Disabled",
		"raw:Serial Port 2 Attribute":               "SOL",
		"raw:Software Controlled T-States":          "Enabled",
		"raw:SpeedStep (P-States)":                  "Enabled",
		"raw:Spin Up Device":                        "Disabled",
		"raw:Stale AtoS":                            "Auto",
		"raw:Static Virtual Lockstep Mode":          "Disabled",
		"raw:Stop Bits":                             "1",
		"raw:Storage Hierarchy":                     "Enabled",
		"raw:Suppress PTT Commands":                 "Disabled",
		"raw:TXT Support":                           "Disabled",
		"raw:Terminal Type":                         "VT-UTF8",
		"raw:Turbo Mode":                            "Enabled",
		"raw:VGA Priority":                          "Onboard",
		"raw:WHEA Support":                          "Enabled",
		"raw:Wait For \"F1\" If Error":              "Enabled",
		"raw:Watch Dog Function":                    "Disabled",
		"raw:When Log is Full":                      "Do Nothing",
		"raw:XHCI Hand-off":                         "Enabled",
		"raw:XPT Prefetch":                          "Disabled",
		"raw:sSATA Controller":                      "Enabled",
		"raw:sSATA Device Type":                     "Hard Disk Drive",
		"raw:sSATA RAID Option ROM/UEFI Driver":     "Legacy",
		"raw:sSATA RSTe Boot Info":                  "Enabled",
		"raw:tCCD_L Relaxation":                     "Auto",
		"raw:tRFC Optimization for 16Gb Based DIMM": "Disabled",
		"raw:tRWSR Relaxation":                      "Disabled",
	}

	b, err := ioutil.ReadFile("../fixtures/supermicro/x11dph-t/bios.xml")
	if err != nil {
		t.Error(err)
	}

	s := NewFakeSMCSum(bytes.NewReader(b))
	c, err := s.parseBIOSConfig(context.TODO())
	assert.NoError(t, err)
	assert.Equal(t, expected, c)
}
