name: Release

on:
  push:
    tags:
      - 'v*.*.*'
      - 'v*.*.*-staging'

jobs:
  container-main:
    uses: metal-toolbox/container-push/.github/workflows/container-push.yml@main
    with:
      name: ironlib
      tag: ${GITHUB_REF_NAME}
      dockerfile_path: Dockerfile
