name: release docker image

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
      - 'v*.*.*-staging'

jobs:
  build:
    permissions:
      contents: read
      packages: write
      id-token: write # needed for signing the images with GitHub OIDC Token
    runs-on: ubuntu-latest
    name: build, release, sign
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: install cosign
        uses: sigstore/cosign-installer@main

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push image
        id: dockerbuild
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ghcr.io/metal-toolbox/ironlib:${{ github.ref_name }}

      - name: Sign the images with GitHub OIDC Token
        run: cosign sign ghcr.io/metal-toolbox/ironlib:${{ github.ref_name }}
        env:
          COSIGN_EXPERIMENTAL: true

      - name: Scan image
        id: scan
        uses: anchore/scan-action@v3
        with:
          image: ghcr.io/metal-toolbox/ironlib:latest
          acs-report-enable: true
          # TODO(jaosorior): Fail build once we migrate off CentOS.
          fail-build: false

      - uses: anchore/sbom-action/download-syft@v0.12.0

      # TODO(jaosorior): Uncomment once we migrate off CentOS.
      # - name: upload Anchore scan SARIF report
      #   uses: github/codeql-action/upload-sarif@v2
      #   with:
      #     sarif_file: ${{ steps.scan.outputs.sarif }}
      #   # This should run even if we fail the container scan
      #   if: always()

      - name: Inspect action SARIF report
        run: cat ${{ steps.scan.outputs.sarif }}
        # This should run even if we fail the container scan
        if: always()
