name: publish image
on:
  push:
    branches:
      - main
    tags:
      - 'v.*.*.*'
      - 'v.*.*.*-staging'

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
      - name: Checkout code
        uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          args: --config .golangci.yml
          version: v1.45.2
      - name: Test
        run: go test ./...
  build:
    runs-on: ubuntu-latest
    needs: [lint-test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set latest tag
        id: releaseSetLatestTag
        shell: bash
        run: |
          if [[ "$GITHUB_REF" =~ ^refs/tags/v*.*.*-staging ]]; then
            echo -n "::set-output name=latest::false"
          else
            echo -n "::set-output name=latest::true"
          fi

      - name: Set latest staging tag
        id: releaseSetLatestStagingTag
        shell: bash
        run: |
          if [[ "$GITHUB_REF" =~ ^refs/tags/v*.*.*-staging ]]; then
            echo -n "::set-output name=latest-staging::true"
          else
            echo -n "::set-output name=latest-staging::false"
          fi

      - name: Docker meta
        uses: docker/metadata-action@v3
        id: meta_docker_ironlib
        with:
          images: quay.io/packet/ironlib
          flavor: |
            latest=${{ steps.releaseSetLatestTag.outputs.latest }}
          tags: |
            type=raw,enable=${{ steps.releaseSetLatestStagingTag.outputs.latest-staging }},value=latest-staging
            type=ref,event=branch
            type=semver,pattern={{raw}}

      - name: Login to Quay registry
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push ironlib docker image
        id: docker_build_ironlib
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./
          file: Dockerfile
          tags: "${{ steps.meta_docker_ironlib.outputs.tags }}"
